### PR TITLE
Actually closing #4

### PR DESCRIPTION
**Pull request by prototriangle**
Closes https://github.com/CreatEDHack/createdhack.github.io/issues/4

### CODE REVIEW

**Comment by prototriangle** [comment]
N.B. Still working on schedule

**Comment by notexactlyawe** [comment]
It's worth just noting that we're not requiring attendees to be students

**Comment by notexactlyawe** [comment]
Also we should add an under-18s FAQ since we're not allowing them to the event (paperwork headache)

**Comment by prototriangle** [comment]
Should I change:
- question:      "Do I need to be a student to attend?"
      answer:        >
        Yes. Only students who are currently enrolled at a college/university or
        have graduated within the past 12 months are eligible to attend.

for:
- question:      "Do I need to be over 18yrs attend?"
      answer:        >
        Yes. Currently we cannot accommodate attendees under the age of 18.

**Comment by prototriangle** [comment]
Or something like that^

**Review by notexactlyawe — APPROVED** [review]

**Comment by notexactlyawe** [comment]
The one thing left to do with this is to add in a button at the top that links to the map, but I'll stick that in an issue

**Pull request merged**
