### PR TITLE
Add Compsoc logo to Tier 2

### PR DESCRIPTION
**Pull request by aga11313**
I've added the Compsoc logo but I can't figure out how to center it with respect to the FDM logo.
@prototriangle @notexactlyawe can you help?

### CODE REVIEW

**Comment by prototriangle** [comment]
Is actually quite difficult to center it with the fdm logo being so tall

**Comment by prototriangle** [comment]
s

**Comment by prototriangle** [comment]
@aga11313 Could we use the stacked (taller) logo?

**Comment by prototriangle** [comment]
There is a quick fix however that will work in modern browsers

**Comment by prototriangle** [comment]
Have added fix and have resolved #50

**Comment by notexactlyawe** [comment]
I'm getting the tier 2 sponsors right-aligned on mine. The desired behaviour is to be centered in my head.
screenshot from 2018-03-26 12-10-39

**Comment by prototriangle** [comment]
Oops. I forgot to fix the bootstrap padding. I know how to fix but can't be at my computer until around 2

**Comment by aga11313** [comment]
@prototriangle did you have time to fix this yet?

**Pull request merged**
